version: '3'
services:
  app:
    image: guoxiangke/gted
    build:
      context: .
      dockerfile: "Dockerfile"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./bot:/usr/src/app/bot
      - ./.env:/usr/src/app/.env
      # - ./bot/config:/usr/src/app/bot/config
      - ./19_Psalm:/usr/src/app/bot/files/19_Psalm # resources(mp3) for one cron task
