version: '3'
services:
  app:
    image: guoxiangke/gted
    build:
      context: .
      dockerfile: "Dockerfile"
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/app/.env
      - ./bot/forward.json:/usr/src/app/bot/forward.json
      - ./bot/autoReply.json:/usr/src/app/bot/autoReply.json
      - ./bot/roomAutoJoin.json:/usr/src/app/bot/roomAutoJoin.json
