version: '3'
services:
  app:
    image: guoxiangke/gted
    build:
      context: .
      dockerfile: "Dockerfile"
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/app/.env
      - ./forward.json:/usr/src/app/forward.json
